require("harpoon"):setup()
vim.keymap.set("n", "<leader>a", function() require("harpoon"):list():add() end)
vim.keymap.set("n", "<leader>q", function() require("harpoon"):list():select(1) end)
vim.keymap.set("n", "<leader>w", function() require("harpoon"):list():select(2) end)
vim.keymap.set("n", "<leader>e", function() require("harpoon"):list():select(3) end)
vim.keymap.set("n", "<leader>r", function() require("harpoon"):list():select(4) end)
vim.keymap.set("n", "<C-e>", function() require("harppon").ui:toggle_quick_menu(require("harpoon"):list()) end)
